services:
  flask-api:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: model_api
    ports:
      - "5000:5000"
    volumes:
      - ./app/static:/app/static
    restart: "no"
    networks:
      - wxnetwork
networks:
  wxnetwork:
    driver: bridge